from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any, ClassVar

from fastapi import Request
from sqlalchemy import DateTime, MetaData
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import DeclarativeBase

# Explicit naming keeps constraint names stable across autogenerated migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Invariant 1: every timestamp is timezone-aware (stored as UTC).
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        datetime: DateTime(timezone=True),
        dict[str, Any]: JSONB,
        list[str]: JSONB,
    }


async def get_session(request: Request) -> AsyncIterator[AsyncSession]:
    """One AsyncSession per request."""
    async with request.app.state.session_factory() as session:
        yield session
