/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_admin_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide */
        patch: operations["decide_api_v1_admin_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_admin_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_api_v1_admin_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/employees/import/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Template */
        get: operations["import_template_api_v1_admin_employees_import_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/employees/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Employees */
        post: operations["import_employees_api_v1_admin_employees_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_admin_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_api_v1_admin_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/employees/{employee_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_admin_employees__employee_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/employees/{employee_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock */
        post: operations["unlock_api_v1_admin_employees__employee_id__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team */
        get: operations["team_api_v1_employees_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/masters/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Masters */
        get: operations["list_masters_api_v1_admin_masters__kind__get"];
        put?: never;
        /** Create Master */
        post: operations["create_master_api_v1_admin_masters__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/masters/{kind}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Master */
        delete: operations["delete_master_api_v1_admin_masters__kind___item_id__delete"];
        options?: never;
        head?: never;
        /** Update Master */
        patch: operations["update_master_api_v1_admin_masters__kind___item_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_v1_admin_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_v1_admin_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_api_v1_admin_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_admin_roles__role_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_employees_api_v1_admin_employees_import_post */
        Body_import_employees_api_v1_admin_employees_import_post: {
            /** File */
            file: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Employees Total */
            employees_total: number;
            /** Employees Active */
            employees_active: number;
            /** Employees Inactive */
            employees_inactive: number;
            /** Pending Devices */
            pending_devices: number;
        };
        /**
         * DeviceConflict
         * @description The other employee this phone is currently active for.
         */
        DeviceConflict: {
            /** User Id */
            user_id: number;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
        };
        /** DeviceCounts */
        DeviceCounts: {
            /** Pending */
            pending: number;
            /** Active */
            active: number;
            /** Revoked */
            revoked: number;
        };
        /** DeviceDecision */
        DeviceDecision: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject" | "revoke";
        };
        /** DeviceInfo */
        DeviceInfo: {
            /** Device Id */
            device_id: string;
            /** Model */
            model: string;
            /** Os */
            os: string;
            /** App Version */
            app_version: string;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Emp Code */
            emp_code: string;
            /** User Name */
            user_name: string;
            /** Device Id */
            device_id: string;
            /** Model */
            model: string;
            /** Os */
            os: string;
            /** App Version */
            app_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "pending" | "revoked";
            /** Approved By */
            approved_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            conflict: components["schemas"]["DeviceConflict"] | null;
        };
        /** DevicePage */
        DevicePage: {
            /** Items */
            items: components["schemas"]["DeviceOut"][];
            counts: components["schemas"]["DeviceCounts"];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Mobile */
            mobile: string;
            /** Email */
            email?: string | null;
            /** Designation Id */
            designation_id: number;
            /** Department Id */
            department_id?: number | null;
            /** Role Id */
            role_id: number;
            /** Manager Id */
            manager_id?: number | null;
            /**
             * Joined On
             * Format: date
             */
            joined_on: string;
            /**
             * Field Eligible
             * @default false
             */
            field_eligible: boolean;
            /** Password */
            password?: string | null;
        };
        /** EmployeeCreated */
        EmployeeCreated: {
            employee: components["schemas"]["EmployeeOut"];
            /** Temporary Password */
            temporary_password: string | null;
        };
        /** EmployeeOut */
        EmployeeOut: {
            /** Id */
            id: number;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Mobile */
            mobile: string;
            /** Email */
            email: string | null;
            role: components["schemas"]["Ref"];
            designation: components["schemas"]["Ref"];
            department: components["schemas"]["Ref"] | null;
            /** Manager Id */
            manager_id: number | null;
            /** Field Eligible */
            field_eligible: boolean;
            /** Status */
            status: string;
            /**
             * Joined On
             * Format: date
             */
            joined_on: string;
            /** Must Change Password */
            must_change_password: boolean;
            /** Locked Until */
            locked_until: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmployeePage */
        EmployeePage: {
            /** Items */
            items: components["schemas"]["EmployeeOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EmployeeUpdate
         * @description Partial update: only the fields sent are changed (null clears email/department/manager).
         */
        EmployeeUpdate: {
            /** Name */
            name?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Email */
            email?: string | null;
            /** Designation Id */
            designation_id?: number | null;
            /** Department Id */
            department_id?: number | null;
            /** Role Id */
            role_id?: number | null;
            /** Manager Id */
            manager_id?: number | null;
            /** Joined On */
            joined_on?: string | null;
            /** Field Eligible */
            field_eligible?: boolean | null;
            /** Status */
            status?: ("active" | "inactive") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * Storage
             * @enum {string}
             */
            storage: "ok" | "error";
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            checks: components["schemas"]["HealthChecks"];
        };
        /** ImportCredential */
        ImportCredential: {
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Temporary Password */
            temporary_password: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Dry Run */
            dry_run: boolean;
            /** Total Rows */
            total_rows: number;
            /** Created */
            created: number;
            /** Errors */
            errors: components["schemas"]["ImportRowError"][];
            /** Credentials */
            credentials: components["schemas"]["ImportCredential"][];
        };
        /** ImportRowError */
        ImportRowError: {
            /** Row */
            row: number;
            /** Message */
            message: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Identifier */
            identifier: string;
            /** Password */
            password: string;
            /**
             * Client
             * @enum {string}
             */
            client: "web" | "mobile";
            device?: components["schemas"]["DeviceInfo"] | null;
        };
        /** MasterIn */
        MasterIn: {
            /** Name */
            name: string;
        };
        /** MeDevice */
        MeDevice: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "pending" | "revoked";
            /** Pending Reason */
            pending_reason: "phone_in_use" | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            /** Mobile */
            mobile: string;
            /** Email */
            email: string | null;
            role: components["schemas"]["Ref"];
            /** Permissions */
            permissions: string[];
            designation: components["schemas"]["Ref"];
            department: components["schemas"]["Ref"] | null;
            /** Manager Id */
            manager_id: number | null;
            /** Field Eligible */
            field_eligible: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /**
             * Client
             * @enum {string}
             */
            client: "web" | "mobile";
            device: components["schemas"]["MeDevice"] | null;
        };
        /** Ref */
        Ref: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Name */
            name: string;
            /** Permissions */
            permissions: string[];
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Permissions */
            permissions: string[];
            /** Is System */
            is_system: boolean;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Name */
            name?: string | null;
            /** Permissions */
            permissions?: string[] | null;
        };
        /** TeamMemberOut */
        TeamMemberOut: {
            /** Id */
            id: number;
            /** Emp Code */
            emp_code: string;
            /** Name */
            name: string;
            designation: components["schemas"]["Ref"];
            /** Field Eligible */
            field_eligible: boolean;
            /** Manager Id */
            manager_id: number | null;
        };
        /** TeamPage */
        TeamPage: {
            /** Items */
            items: components["schemas"]["TeamMemberOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** TemporaryPassword */
        TemporaryPassword: {
            /** Temporary Password */
            temporary_password: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            /** Must Change Password */
            must_change_password: boolean;
            /** Device Status */
            device_status: ("active" | "pending" | "revoked") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_devices_api_v1_admin_devices_get: {
        parameters: {
            query?: {
                status?: ("active" | "pending" | "revoked") | null;
                user_id?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_admin_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    list_employees_api_v1_admin_employees_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: ("active" | "inactive") | null;
                role_id?: number | null;
                department_id?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_api_v1_admin_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_template_api_v1_admin_employees_import_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_employees_api_v1_admin_employees_import_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_employees_api_v1_admin_employees_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_api_v1_admin_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_api_v1_admin_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_admin_employees__employee_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_api_v1_admin_employees__employee_id__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_api_v1_employees_team_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_masters_api_v1_admin_masters__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "departments" | "designations";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ref"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_master_api_v1_admin_masters__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "departments" | "designations";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ref"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_master_api_v1_admin_masters__kind___item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "departments" | "designations";
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_master_api_v1_admin_masters__kind___item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "departments" | "designations";
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ref"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_admin_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
        };
    };
    create_role_api_v1_admin_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_admin_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_admin_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
